[versions]
minestom = "2025.07.03-1.21.5" # https://github.com/Minestom/Minestom/releases
logback = "1.5.18" # https://github.com/qos-ch/logback/releases

[libraries]
minestom = { group = "net.minestom", name = "minestom", version.ref = "minestom" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[bundles]
server = ["minestom", "logback"]